language: php

php:
  - 5.3.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.3.3

before_script:
  - composer install --no-interaction --dev --prefer-source

script: php tests/lint -R app && php tests/lint -R tests/cases && phpunit --configuration tests/phpunit.xml

notifications:
  email: false
